resolver: lts-13.26

packages:
  - .

nix:
    packages: [openssh,git]

allow-newer: true

extra-deps:
  - o-clock-1.0.0.1
  - tasty-hedgehog-0.1.0.2

  - git: https://github.com/input-output-hk/universum
    commit: 15f7db758ff5a24b874de2247f6f7a4576562da5
